version: '3.8'
services:
  slim_server:
      container_name: slim-server
      image: slim-server
      ports: 
        - '5200:5200'
      volumes:
        - ./server:/go/dev
  slim_spa: 
    container_name: slim-spa
    image: slim-spa
    ports:
    - '5201:5201'
    volumes:
        - ./spa:/node/dev
    depends_on:
      - slim_server
  # mysql_db: 
  #   container_name: mysql_db
  #   restart: always
  #   image: mysql:8.0.30
  #   ports:
  #     - '3306:3306'
  #   volumes:
  #     - ./database:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password