version: '3.8'
services:
  slim_server:
      container_name: slim-server
      image: sti-munoz/slim-server
      ports: 
        - '5200:5200'
      volumes:
        - ./server:/go/dev
      environment:
          MIGRATE: ${DB_DRIVER}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@slim_postgres/${POSTGRES_DB}?sslmode=disable
          DB_DRIVER: ${DB_DRIVER}
          DB_HOST: ${DB_HOST}
          DB_PORT : ${DB_PORT}
          DB_NAME: ${POSTGRES_DB}
          DB_USERNAME : ${POSTGRES_USER}
          DB_PASSWORD: ${POSTGRES_PASSWORD}
          SPA_ADMIN_URL: ${SPA_ADMIN_URL}
          SPA_CLIENT_URL: ${SPA_ADMIN_URL}
      depends_on:
        - slim_postgres
  slim_spa_admin: 
    container_name: slim-spa-admin
    image: sti-munoz/slim-spa-admin
    ports:
    - '5201:5201'
    volumes:
        - /node/dev/node_modules
        - ./spa-admin:/node/dev
    depends_on:
      - slim_server
  slim_spa_client: 
    container_name: slim-spa-client
    image: sti-munoz/slim-spa-client
    ports:
    - '5202:5202'
    volumes:
        - /node/dev/node_modules
        - ./spa-client:/node/dev
    depends_on:
      - slim_server
  slim_postgres: 
    container_name: slim-postgres
    restart: always
    image: postgres:15.0-alpine
    ports:
      - '5203:5432'
    volumes:
      - ./database:/var/lib/postgresql/data 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  slim_pgadmin:
    container_name: slim-pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - slim_postgres
    volumes:
    - ./pgadmin:/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5204:80"
  slim_rabbitmq:
      image: rabbitmq:3.11.9-management-alpine
      container_name: slim-rabbitmq
      restart: always
      depends_on:
        - slim_server
      ports:
        - '5205:5672'
        - '5206:15672'
      environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

    
