name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker images
        uses: actions/checkout@v3

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{DOCKERHUB_USERNAME}}
          password: ${{DOCKERHUB_ACCESS_TOKEN}}
      - name: Build the Docker image
        run: docker build -t ryanali12/sti-munoz-library-server:latest -f ./server/Dockerfile
