name: Docker Production Images CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build docker images
        uses: actions/checkout@v3

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build Production Server Docker Image
        run: docker build ./server --file ./server/Dockerfile.prod --tag ryanali12/sti-munoz-library-server-prod:latest
      # - name: Build Production Admin Application Docker Image
      #   run: docker build ./admin_app --file ./admin_app/Dockerfile.prod --tag ryanali12/sti-munoz-library-admin-app-prod:latest
      # - name: Build Production Client Application Docker Image
      #   run: docker build ./client_app --file ./client_app/Dockerfile.prod --tag ryanali12/sti-munoz-library-client-app-prod:latest

      - name: Push Production Server Image
        run: docker push ryanali12/sti-munoz-library-server-prod:latest
      # - name: Push Production Admin Application Image
      #   run: docker push ryanali12/sti-munoz-library-admin-app-prod:latest
      # - name: Push Production Client Application Image
      #   run: docker push ryanali12/sti-munoz-library-client-app-prod:latest
